### PR TITLE
Photo upload

### PR DESCRIPTION
**Pull request by pahan35**
Implement photo upload for available module accordingly to [API doc](https://www.zoho.eu/crm/help/api/uploadphoto.html)

If you have some suggestion about better place for this function I ready to consider them.

### CODE REVIEW

**Comment by pahan35** [comment]
When you successfully accept my submitted pull requests I going to implement [delete/download][File/Photo] API methods

**Comment by pahan35** [comment]
@ahmader thanks for accepting my changes.

During next week I'm going to implement other files/photo method

**Comment by ahmader** [comment]
@pahan35 Thanks for your contributions.

Feel free to submit a PR with your name/email to the `packages.json` file **contributors section**.

**Comment by pahan35** [comment]
@ahmader thanks. I'll add it after all files API implementation.

This package is really cool and simplify work with Zoho a lot.

If you have some further ideas for improving this package I can help with it.

From my side I will improve that missed possibilities which I will notice myself.

**Pull request merged**
