### PR TITLE
Send data for insert/update in request body

### PR DESCRIPTION
**Pull request by karolisg**
This change allows sending data in request body. Now it is send in url and has length limitations on ZOHO side

### CODE REVIEW

**Comment by karolisg** [comment]
@ahmader Please let me know if you are still maintaining this library. I am using a lot zoho API integrations and need some changes, so if you are not maintaining, I will start publishing my own version to npm.

**Comment by interlock** [comment]
@karolisg May I suggest that we ask @ahmader to add you to this project instead of forking?

I started this off and passed it to @ahmader when we moved away from Zoho. I am unfortunately not a repo admin any more so I can't help out here, but would like to see it keep on moving if people are using it.

@ahmader If you are in the same boat I was a few years ago, maybe pass the torch and transfer the repo ownership?

**Comment by ahmader** [comment]
Thanks @karolisg I will merge your pull requests ASAP sorry for the delay, we use zoho extensively too. I just want to make sure I don't break backward compatibility to our projects. 

@interlock thanks for pinging me to answer, I was welling to add @karolisg to "collaborators" panel on github. Would this give him access to merge requests or how can I add him? Any help appreciated.

**Comment by interlock** [comment]
@ahmader I believe just adding @karolisg to the collaborators panel is enough :+1:

**Comment by ahmader** [comment]
@karolisg can you please pass the `npm test` 

I want to run an integration test on this before accepting.

Thanks

**Comment by karolisg** [comment]
@ahmader Fixed test.

**Pull request closed without merging**
